name: flutter_imagepicker_test
description: Flutter ImagePicker test

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:

  sdk: ">=2.15.1 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  image_picker: ^0.8.4+7
  path_provider: ^2.0.8

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
